services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
#    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
      - pipelines
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
      - OPENAI_API_KEY=0p3n-w3bu!
      - OPENAI_API_BASE_URL=http://pipelines:9099
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - cosmic_net

  pipelines:
    build:
      context: ./../pipelines-openwebui
      dockerfile: Dockerfile
    container_name: pipelines
    volumes:
      - ./../pipelines-openwebui:/app/pipelines
    #    pull_policy: always
    ports:
      - '9099:9099'
    tty: true
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    #    image: pipelines/pipelines:latest
    networks:
      - cosmic_net

volumes:
  ollama: {}
  open-webui: {}
  pipelines: {}

networks:
  cosmic_net:
    driver: bridge
